"""Initial migration

Revision ID: 001_initial
Revises:
Create Date: 2024-01-15 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_user_tenant_email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('cloud_accounts',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'account_id', name='uq_cloud_account_tenant_provider_id')
    )
    op.create_index(op.f('ix_cloud_accounts_tenant_id'), 'cloud_accounts', ['tenant_id'], unique=False)
    op.create_table('k8s_clusters',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('k8s_version', sa.String(length=30), nullable=True),
    sa.Column('cloud_account_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_cluster_tenant_name')
    )
    op.create_index(op.f('ix_k8s_clusters_tenant_id'), 'k8s_clusters', ['tenant_id'], unique=False)
    op.create_table('agents',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'DEPRECATED', name='agent_status'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_tenant_id'), 'agents', ['tenant_id'], unique=False)
    op.create_table('cost_line_items',
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('cloud_account_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('line_item_type', postgresql.ENUM('COMPUTE', 'MEMORY', 'STORAGE', 'NETWORK', 'LICENSING', 'OTHER', name='cost_line_item_type'), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.String(length=512), nullable=True),
    sa.Column('usage_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('usage_unit', sa.String(length=50), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_line_items_cloud_account_id'), 'cost_line_items', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_cost_line_items_tenant_id'), 'cost_line_items', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cost_line_items_usage_start'), 'cost_line_items', ['usage_start'], unique=False)
    op.create_table('k8s_nodes',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('cluster_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('READY', 'NOT_READY', 'UNKNOWN', name='k8s_node_status'), nullable=False),
    sa.Column('instance_type', sa.String(length=100), nullable=True),
    sa.Column('cpu_capacity', sa.Integer(), nullable=True),
    sa.Column('memory_capacity_mb', sa.BigInteger(), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('taints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'name', name='uq_node_cluster_name')
    )
    op.create_index(op.f('ix_k8s_nodes_cluster_id'), 'k8s_nodes', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_k8s_nodes_tenant_id'), 'k8s_nodes', ['tenant_id'], unique=False)
    op.create_table('orchestration_jobs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('agent_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('cluster_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', postgresql.ENUM('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='job_status'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.BigInteger(), nullable=True),
    sa.Column('completion_tokens', sa.BigInteger(), nullable=True),
    sa.Column('parent_job_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_job_id'], ['orchestration_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orchestration_jobs_agent_id'), 'orchestration_jobs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_orchestration_jobs_cluster_id'), 'orchestration_jobs', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_orchestration_jobs_parent_job_id'), 'orchestration_jobs', ['parent_job_id'], unique=False)
    op.create_index(op.f('ix_orchestration_jobs_status'), 'orchestration_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_orchestration_jobs_tenant_id'), 'orchestration_jobs', ['tenant_id'], unique=False)
    op.create_table('accelerators',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('node_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('accelerator_type', postgresql.ENUM('GPU', 'TPU', 'LPU', 'OTHER', name='accelerator_type'), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('vram_gb', sa.Integer(), nullable=True),
    sa.Column('compute_units', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('AVAILABLE', 'IN_USE', 'RESERVED', 'OFFLINE', name='accelerator_status'), nullable=False),
    sa.Column('hourly_cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cloud_account_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['k8s_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accelerators_node_id'), 'accelerators', ['node_id'], unique=False)
    op.create_index(op.f('ix_accelerators_tenant_id'), 'accelerators', ['tenant_id'], unique=False)
    op.create_table('k8s_pods',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('cluster_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('node_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('orchestration_job_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phase', postgresql.ENUM('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'UNKNOWN', name='pod_phase'), nullable=False),
    sa.Column('cpu_request_m', sa.Integer(), nullable=True),
    sa.Column('memory_request_mb', sa.Integer(), nullable=True),
    sa.Column('cpu_limit_m', sa.Integer(), nullable=True),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['k8s_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['k8s_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['orchestration_job_id'], ['orchestration_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k8s_pods_cluster_id'), 'k8s_pods', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_k8s_pods_orchestration_job_id'), 'k8s_pods', ['orchestration_job_id'], unique=False)
    op.create_index(op.f('ix_k8s_pods_tenant_id'), 'k8s_pods', ['tenant_id'], unique=False)
    op.create_table('job_cost_aggregates',
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('compute_cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('accelerator_cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('storage_cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('network_cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('llm_token_cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('other_cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('accelerator_utilization_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('idle_cost_usd', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('cost_per_token', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['orchestration_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_index(op.f('ix_job_cost_aggregates_tenant_id'), 'job_cost_aggregates', ['tenant_id'], unique=False)
    op.create_table('job_resource_usage',
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('accelerator_id', postgresql.UUID(as_uuid=False), nullable=True),
    sa.Column('accelerator_type', postgresql.ENUM('GPU', 'TPU', 'LPU', 'OTHER', name='accelerator_type'), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('avg_utilization_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_memory_used_gb', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('peak_memory_gb', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['accelerator_id'], ['accelerators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['orchestration_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_resource_tenant_job', 'job_resource_usage', ['tenant_id', 'job_id'], unique=False)
    op.create_index(op.f('ix_job_resource_usage_accelerator_id'), 'job_resource_usage', ['accelerator_id'], unique=False)
    op.create_index(op.f('ix_job_resource_usage_job_id'), 'job_resource_usage', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_resource_usage_tenant_id'), 'job_resource_usage', ['tenant_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('impact', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='recommendation_impact'), nullable=False),
    sa.Column('effort', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='recommendation_effort'), nullable=False),
    sa.Column('savings_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'IN_PROGRESS', 'DONE', 'DISMISSED', name='recommendation_status'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_tenant_id'), 'recommendations', ['tenant_id'], unique=False)
    op.create_table('resource_hourly_metrics',
    sa.Column('id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('accelerator_id', postgresql.UUID(as_uuid=False), nullable=False),
    sa.Column('hour_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avg_utilization_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('max_utilization_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_memory_used_gb', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('peak_memory_gb', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('avg_power_watts', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('avg_temp_celsius', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('idle_fraction', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['accelerator_id'], ['accelerators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'accelerator_id', 'hour_ts', name='uq_hourly_metric_tenant_acc_hour')
    )
    op.create_index('ix_hourly_metric_tenant_hour', 'resource_hourly_metrics', ['tenant_id', 'hour_ts'], unique=False)
    op.create_index(op.f('ix_resource_hourly_metrics_accelerator_id'), 'resource_hourly_metrics', ['accelerator_id'], unique=False)
    op.create_index(op.f('ix_resource_hourly_metrics_tenant_id'), 'resource_hourly_metrics', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_hourly_metrics_tenant_id'), table_name='resource_hourly_metrics')
    op.drop_index(op.f('ix_resource_hourly_metrics_accelerator_id'), table_name='resource_hourly_metrics')
    op.drop_index('ix_hourly_metric_tenant_hour', table_name='resource_hourly_metrics')
    op.drop_table('resource_hourly_metrics')
    op.drop_index(op.f('ix_recommendations_tenant_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_job_resource_usage_tenant_id'), table_name='job_resource_usage')
    op.drop_index(op.f('ix_job_resource_usage_job_id'), table_name='job_resource_usage')
    op.drop_index(op.f('ix_job_resource_usage_accelerator_id'), table_name='job_resource_usage')
    op.drop_index('ix_job_resource_tenant_job', table_name='job_resource_usage')
    op.drop_table('job_resource_usage')
    op.drop_index(op.f('ix_job_cost_aggregates_tenant_id'), table_name='job_cost_aggregates')
    op.drop_table('job_cost_aggregates')
    op.drop_index(op.f('ix_k8s_pods_tenant_id'), table_name='k8s_pods')
    op.drop_index(op.f('ix_k8s_pods_orchestration_job_id'), table_name='k8s_pods')
    op.drop_index(op.f('ix_k8s_pods_cluster_id'), table_name='k8s_pods')
    op.drop_table('k8s_pods')
    op.drop_index(op.f('ix_accelerators_tenant_id'), table_name='accelerators')
    op.drop_index(op.f('ix_accelerators_node_id'), table_name='accelerators')
    op.drop_table('accelerators')
    op.drop_index(op.f('ix_orchestration_jobs_tenant_id'), table_name='orchestration_jobs')
    op.drop_index(op.f('ix_orchestration_jobs_status'), table_name='orchestration_jobs')
    op.drop_index(op.f('ix_orchestration_jobs_parent_job_id'), table_name='orchestration_jobs')
    op.drop_index(op.f('ix_orchestration_jobs_cluster_id'), table_name='orchestration_jobs')
    op.drop_index(op.f('ix_orchestration_jobs_agent_id'), table_name='orchestration_jobs')
    op.drop_table('orchestration_jobs')
    op.drop_index(op.f('ix_k8s_nodes_tenant_id'), table_name='k8s_nodes')
    op.drop_index(op.f('ix_k8s_nodes_cluster_id'), table_name='k8s_nodes')
    op.drop_table('k8s_nodes')
    op.drop_index(op.f('ix_cost_line_items_usage_start'), table_name='cost_line_items')
    op.drop_index(op.f('ix_cost_line_items_tenant_id'), table_name='cost_line_items')
    op.drop_index(op.f('ix_cost_line_items_cloud_account_id'), table_name='cost_line_items')
    op.drop_table('cost_line_items')
    op.drop_index(op.f('ix_agents_tenant_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_k8s_clusters_tenant_id'), table_name='k8s_clusters')
    op.drop_table('k8s_clusters')
    op.drop_index(op.f('ix_cloud_accounts_tenant_id'), table_name='cloud_accounts')
    op.drop_table('cloud_accounts')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###