"""add username to users

Revision ID: ff70f00498d6
Revises: 001_initial
Create Date: 2026-05-19 14:00:52.539698

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff70f00498d6'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('auth_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('agents', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=False))
    op.create_unique_constraint('uq_user_tenant_username', 'users', ['tenant_id', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_tenant_username', 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('agents', 'last_seen_at')
    op.drop_column('agents', 'auth_token_expires_at')
    # ### end Alembic commands ###